### ISSUE TITLE
Are you still supporting this?

### ISSUE THREAD

**Issue by rossdargan** [danielperna84/ha-philipsjs#1]
It looks like jointSPACE is woefully out of date on more modern tvs. 

I'm working through seeing what needs to change, and it's a fair bit. Happy to do pull requests if you are still planning on supporting this?

**Comment by danielperna84** [comment]
You are right. The new TVs seem to have some changes. There is a thread at the Home Assistant forum where a user took my module as a reference for a custom coponent: https://community.home-assistant.io/t/philips-android-tv-component/17749/4

If you manage to retain compatibility with the older TVs (that's what this module is mode for after all), then feel free to submit your pull requests. I don't have a Philips TV anymore. So I can also add you as a contributor with write permissions so you can take over lator on.

**Comment by rossdargan** [comment]
Ah fantastic - Hadn't seen that thread!

If we make progress I'll get back in touch!

Thanks for yous help.
