### ISSUE TITLE
Stopped working with PUS9109 

### ISSUE THREAD

**Issue by kingel** [danielperna84/ha-philipsjs#2]
Since two weeks i get this error with my tv

  File "/srv/homeassistant/lib/python3.5/site-packages/haphilipsjs/__init__.py", line 33, in _getReq
    return json.loads(resp.text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Is this a know issue?

**Comment by danielperna84** [comment]
I don't own a Philips TV anymore, so I can't comment on this. Maybe open a thread in the HASS forum if anyone has similar problems.

**Comment by fliphess** [comment]
For future reference: Chances are your TV is a Philips android one, which has a slighly different implementation of the jointspace api.

This example appears to be working for me at the time of writing: https://github.com/suborb/philips_android_tv/blob/master/philips.py

I'll try to take a dive and look into it later this week combining the two into something useful for both implementations....

**Comment by frog32** [comment]
I have one of these TVs that is exposing the version 6 of the API. Will check how much effort is needed to get at least the minimal features working.

**Comment by frog32** [comment]
So far I see that simply changing the api version from 1 to 6 fixes most of the functionality. However there are some commands that need a little more to be working again.

**Comment by frog32** [comment]
Are you willing to accept pull requests or should I just fork this? My employer would require that there is a CLA in place if I want to contribute to this.

**Comment by yottatsa** [comment]
Could you please try https://github.com/danielperna84/ha-philipsjs/pull/7? It should support version 6 channeldb better.

**Comment by elupus** [comment]
I think this is fixed now-a-days. Hopefully i'll get https://github.com/home-assistant/core/pull/46422 soonish.
