### ISSUE TITLE
Newest release 3.0.0 not updated correctly?

### ISSUE THREAD

**Issue by Floyer007** [danielperna84/ha-philipsjs#29]
Hi,
I just noticed that my recent approved pull-request changes for the recording function 
https://github.com/danielperna84/ha-philipsjs/compare/2.9.0...3.0.0 aren't available in the python package.

After updating ha-philipsjs via pip, my new functions are not available.

pip shows the correct version for me:
```
pip list | grep ha-philipsjs
ha-philipsjs          3.0.0
```
Opening the installed package manually in vs-code reveals, that the changes are not in.
(~/.local/lib/python3.8/site-packages/haphilipsjs)

The same is true for the HomeAssistant docker-dev-container, where the required version is set to 3.0.0 but my functions are not available (here: /home/vscode/.local/lib/python3.10/site-packages/haphilipsjs).

So I suppose there is a version numbering mismatch right now for some reason?

**Comment by elupus** [comment]
Hmm. Okey i will look. I wonder if i forgot fetching before building the package.

**Comment by elupus** [comment]
I've published 3.0.1 now, which you can use for your development. I've not updated HA yet, since nothing there depends on the new recordings API, so just update the manifest yourself.

**Comment by Floyer007** [comment]
Thanks a lot!
