### ISSUE TITLE
Add support for V5?

### ISSUE THREAD

**Issue by FezVrasta** [danielperna84/ha-philipsjs#3]
As reported [here](https://github.com/home-assistant/home-assistant/issues/13071), may you add support for the v5 API?

**Comment by danielperna84** [comment]
I don't any TV anymore that use the JointSpace API. So as long as nobody contributes there won't be much happening here. I'd actually even prefer if someone would replace me as the package maintainer since I'm not of use anymore for this module.

**Comment by danielperna84** [comment]
Available with 0.0.2.
